# Generated by Django 3.2.6 on 2021-09-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210903_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pay_amt',
        ),
        migrations.AddField(
            model_name='selectplan',
            name='pay_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='plangrowth',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
    ]
