# Generated by Django 3.2.6 on 2021-09-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210910_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='is_able',
            field=models.BooleanField(default=False),
        ),
    ]
